CREATE TABLE CLIENTE (
    ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    ISEXCLUSIVE BOOLEAN NOT NULL,
    SALDO REAL NOT NULL,
    NUMEROCONTA VARCHAR(10) NOT NULL,
    DATANASCIMENTO DATE 
);


CREATE TABLE TRANSACAO_BANCARIA(
    ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    TIPOTRANSACAO CHAR(1) NOT NULL,
    VALOR REAL NOT NULL,
    NUMEROCONTA VARCHAR(10) NOT NULL,
    DATATRANSACAO DATE 
);